input {
	mongodb {
		uri => "mongodb://retrade_admin:mongo_secure_pass_123@mongodb:27017/retrade_exp?authSource=admin"
		placeholder_db_dir => "/usr/share/logstash/mongodb_state"
		placeholder_db_name => "logstash_mongo_state.db"
		collection => "individual_listings"
		batch_size => 5000
	}
}

output {
	elasticsearch {
		hosts => ["http://elasticsearch:9200"]
		index => "individual_listings_index"
		document_id => "%{[_id]}"
	}
}