CREATE TABLE IF NOT EXISTS shops (
	shop_id BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
	uid BINARY(16) NOT NULL,
	shop_name VARCHAR(255) NOT NULL,
	status TINYINT(1) NOT NULL,

	CONSTRAINT pk_shops PRIMARY KEY (shop_id),

	CONSTRAINT fk_shops_uid FOREIGN KEY (uid)
		REFERENCES users(uid)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	CONSTRAINT uq_uid UNIQUE (uid),
	CONSTRAINT uq_shop_name UNIQUE (shop_name)
) ENGINE=InnoDB;