CREATE TABLE IF NOT EXISTS admins (
	admin_id BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	profile_image_url VARCHAR(2048) NULL,
	rbac_role TINYINT(3) NOT NULL DEFAULT 2 COMMENT '2=admin, 3=superAdmin',
	is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=active, 0=inactive',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	last_login DATETIME NULL,

	CONSTRAINT pk_admins PRIMARY KEY (admin_id),
	CONSTRAINT uq_admins_email UNIQUE (email)
) ENGINE=InnoDB;
